baseURL: www.example.com
languageCode: en-us
title: Hugo Hero Theme
theme: hugo-hero-theme
module:
  hugoVersion:
    extended: yes
    min: 0.55.0
params:
  google_analytics_id: ''
  homepage_meta_tags:
    meta_description: Hero is a multipurpose Hugo theme with fullscreen hero images
      and page sections. It contains content types for a business or portfolio site.
    meta_og_description: Hero is a multipurpose Hugo theme with fullscreen hero images
      and page sections. It contains content types for a business or portfolio site.
    meta_og_image: https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png
    meta_og_title: Hugo Hero Theme
    meta_og_type: website
    meta_og_url: https://hugo-hero.netlify.app
    meta_twitter_card: summary
    meta_twitter_creator: '@zerostaticio'
    meta_twitter_site: '@zerostaticio'
menu:
  main:
    - name: Services
      url: /services/
      weight: 1
    - name: Work
      url: /work/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: History
      url: /history/
      weight: 3
    - name: Contact
      url: /contact/
      weight: 4
permalinks:
  pages: /:filename/
  post: /:year/:month/:day/:slug/
