title: Javier Tamayo-Leiva
baseURL: https://example.com
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Javier Tamayo-Leiva
    weight: 1
  es:
    contentDir: content/es
    title: Javier Tamayo-Leiva
    weight: 2
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  body_classes: "avenir bg-washed-blue"
  post_content_classes: "sans-serif bg-washed-blue"
  background_color_class: bg-near-black
  description: Data Science, Data Visualization, Microbial Ecology & Genetics.
  custom_css: ["css/custom.css"]
  
  facebook: ''
  favicon: /images/favicon.png
  featured_image: /images/map.png
  github: https://github.com/TamayoLeivaJ
  gitlab: ''
  instagram: ''
  linkedin: https://www.linkedin.com/in/javier-ignacio-tamayo-leiva-94613267/
  mastodon: ''
  recent_posts_number: 4
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: https://twitter.com/TamayoLeiva_J
  youtube: ''
