title: Javier Tamayo-Leiva
baseURL: https://example.com
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 5
googleAnalytics: ''
enableRobotsTXT: yes

languages:
  en:
    contentDir: content/en
    title: Javier Tamayo-Leiva
    weight: 1
  es:
    contentDir: content/es
    title: Javier Tamayo-Leiva
    weight: 2
    
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
  
params:
  googlefonts: ['Raleway', 'Oswald', 'Roboto']
  fonttitle: 'Oswald'
  fontbody: 'Raleway'
  fontcode: 'Roboto'
  body_classes: "bg-washed-blue"
  post_content_classes: "bg-washed-blue"
  background_color_class: bg-near-black
  description: Data Science, Data Visualization, Microbial Ecology & Genetics.
  custom_css: ["./static/css/custom.css","./static/css/custom_font.css"]
  facebook: ''
  favicon: /images/favicon.png
  featured_image: /images/map.png
  github: https://github.com/TamayoLeivaJ
  gitlab: ''
  instagram: ''
  linkedin: https://www.linkedin.com/in/javier-ignacio-tamayo-leiva-94613267/
  mastodon: ''
  recent_posts_number: 5
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: https://twitter.com/TamayoLeiva_J
  youtube: ''
  orcid: https://orcid.org/0000-0003-2610-6957
  